# This is a basic workflow to help you get started with Actions

name: echo-test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_run:
    workflows: ["CI", "echo-test-dependency"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Test
