# This is a basic workflow to help you get started with Actions

name: echo-test-dependency

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo This should run first, alongside CI
