name: workflow-run-dependency-1

on:
  push

jobs:
  dep-1:
    runs-on: ubuntu-18.04
    steps:
      - name: First
        run: echo First
  
  dep-2:
    runs-on: ubuntu-18.04
    steps:
      - name: Second
        run: echo Second
  
  dep-3:
    runs-on: ubuntu-18.04
    steps:
      - name: Third
        run: echo Third